//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 03.05.2014 13:46:33
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace Moqups.Entities
{
    public class User : IEntity<long>
    {
        public User()
        {
            Pages = new HashSet<Page>();
        }
    
        public virtual long Id
        {
            get;
            set;
        }
        public virtual string Firstname
        {
            get;
            set;
        }
        public virtual string Lastname
        {
            get;
            set;
        }
        public virtual Status Status
        {
            get;
            set;
        }
        public virtual bool IsAdmin
        {
            get;
            set;
        }
        public virtual ICollection<Page> Pages
        {
            get;
            set;
        }
    }
}
